import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { RefreshCw, Search, ShieldAlert } from 'lucide-react'
import { normalizePage, type PageResponse } from '@shared/api/pagination'
import { Button, EmptyState, ErrorNotice, Input, LoadingState, PageHeader, StatusBadge } from '@shared/components/ui'
import { useAuth } from '@features/auth/AuthContext'

interface OperationLog { id: number; username: string; action: string; method: string; path: string; ip: string; status: number; message: string; createdAt: string }
interface SecurityEvent { id: number; type: string; severity: string; ip: string; category: string; message: string; count: number; limit: number; createdAt: string }
interface Restriction { key: string; ip: string; category: string; type: string; remainingSeconds: number; severity: string }
interface SecurityBundle { events: SecurityEvent[]; eventsTotal: number; activeRestrictions: Restriction[]; date: string }

export function StabilityPage() {
  const { api } = useAuth()
  const [keyword, setKeyword] = useState('')
  const [applied, setApplied] = useState('')
  const logs = useQuery({ queryKey: ['operations', 'logs', applied], queryFn: async () => normalizePage(await api!.request<PageResponse<OperationLog>>(`/api/admin/operation-logs?page=0&size=50${applied ? `&keyword=${encodeURIComponent(applied)}` : ''}`), 0, 50), enabled: Boolean(api) })
  return <div><PageHeader title="站点稳定性" description="查看管理员操作日志与服务器请求状态" actions={<Button onClick={() => void logs.refetch()}><RefreshCw className={`h-4 w-4 ${logs.isFetching ? 'animate-spin' : ''}`} />刷新</Button>} /><div className="panel overflow-hidden"><form className="flex max-w-xl gap-2 border-b border-line p-3" onSubmit={(e) => { e.preventDefault(); setApplied(keyword.trim()) }}><div className="relative min-w-0 flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted" /><Input className="pl-9" value={keyword} onChange={(e) => setKeyword(e.target.value)} placeholder="用户名、IP、路径或消息" /></div><Button type="submit">筛选</Button></form>{logs.isPending ? <LoadingState /> : logs.error ? <div className="p-4"><ErrorNotice error={logs.error} /></div> : !logs.data?.content.length ? <EmptyState title="没有操作日志" /> : <div className="overflow-x-auto"><table className="w-full min-w-[980px]"><thead className="bg-[var(--color-surface-subtle)] text-xs text-muted"><tr><th className="table-cell">操作</th><th className="table-cell">账号</th><th className="table-cell">请求</th><th className="table-cell">IP</th><th className="table-cell">状态</th><th className="table-cell">时间</th></tr></thead><tbody>{logs.data.content.map((log) => <tr key={log.id}><td className="table-cell"><p className="font-medium">{log.action}</p><p className="mt-1 max-w-sm truncate text-xs text-muted">{log.message || '-'}</p></td><td className="table-cell">{log.username || '-'}</td><td className="table-cell font-mono text-xs">{log.method} {log.path}</td><td className="table-cell font-mono text-xs">{log.ip}</td><td className="table-cell"><StatusBadge tone={log.status >= 400 ? 'danger' : 'success'}>{log.status}</StatusBadge></td><td className="table-cell text-muted">{new Date(log.createdAt).toLocaleString('zh-CN')}</td></tr>)}</tbody></table></div>}</div></div>
}

export function SecurityPage() {
  const { api } = useAuth()
  const security = useQuery({ queryKey: ['operations', 'security'], queryFn: () => api!.request<SecurityBundle>('/api/admin/security?view=events&page=0&size=50'), enabled: Boolean(api), refetchInterval: 60_000 })
  return <div><PageHeader title="访问安全" description="查看安全事件与当前限制状态" actions={<Button onClick={() => void security.refetch()}><RefreshCw className={`h-4 w-4 ${security.isFetching ? 'animate-spin' : ''}`} />刷新</Button>} />{security.isPending ? <LoadingState /> : security.error ? <ErrorNotice error={security.error} /> : <><section className="mb-5 grid gap-3 md:grid-cols-3"><div className="panel p-4"><p className="text-xs text-muted">当日安全事件</p><p className="mt-2 text-2xl font-semibold">{security.data?.eventsTotal || 0}</p></div><div className="panel p-4"><p className="text-xs text-muted">当前限制</p><p className="mt-2 text-2xl font-semibold">{security.data?.activeRestrictions?.length || 0}</p></div><div className="panel p-4"><p className="text-xs text-muted">统计日期</p><p className="mt-2 text-lg font-semibold">{security.data?.date || '-'}</p></div></section><div className="panel overflow-hidden">{!security.data?.events?.length ? <EmptyState title="没有安全事件" description="当前筛选范围内未记录异常访问。" /> : <div className="overflow-x-auto"><table className="w-full min-w-[920px]"><thead className="bg-[var(--color-surface-subtle)] text-xs text-muted"><tr><th className="table-cell">事件</th><th className="table-cell">IP</th><th className="table-cell">分类</th><th className="table-cell">级别</th><th className="table-cell">计数</th><th className="table-cell">时间</th></tr></thead><tbody>{security.data.events.map((event) => <tr key={event.id}><td className="table-cell"><div className="flex items-start gap-2"><ShieldAlert className="mt-0.5 h-4 w-4 text-amber-600" /><div><p className="font-medium">{event.type}</p><p className="mt-1 max-w-md truncate text-xs text-muted">{event.message || '-'}</p></div></div></td><td className="table-cell font-mono text-xs">{event.ip}</td><td className="table-cell">{event.category || '-'}</td><td className="table-cell"><StatusBadge tone={event.severity === 'high' ? 'danger' : event.severity === 'medium' ? 'warning' : 'neutral'}>{event.severity}</StatusBadge></td><td className="table-cell">{event.count || 0}/{event.limit || '-'}</td><td className="table-cell text-muted">{new Date(event.createdAt).toLocaleString('zh-CN')}</td></tr>)}</tbody></table></div>}</div></>}</div>
}
